### ISSUE TITLE
subaccounts: add subaccounts support

### ISSUE THREAD

**Issue by jonboydell** [logzio/logzio_terraform_client#34]
- [x] get all sub accounts - https://docs.logz.io/api/#operation/getAll
- [x] create a sub account - https://docs.logz.io/api/#operation/createTimeBasedAccount
- [ ] get info on sub accounts - https://docs.logz.io/api/#operation/getAllDetailedTimeBasedAccount
- [ ] get account info by id - https://docs.logz.io/api/#operation/getDetailedTimeBasedAccount
- [x] get sub account by id - https://docs.logz.io/api/#operation/get
- [x] update sub account - https://docs.logz.io/api/#operation/updateTimeBasedAccount
- [x] delete sub account - https://docs.logz.io/api/#operation/deleteTimeBasedAccount

**Comment by yyyogev** [comment]
@jonboydell would you accept a contribution for this one?

**Comment by jonboydell** [comment]
Hi - thank for your contribution - will review today!

**Comment by yyyogev** [comment]
Thanks! 
I'll add a couple more tests in the next few hours or so

**Comment by jonboydell** [comment]
i'm happy if you are - is this ready to merge?

**Comment by yyyogev** [comment]
Not just yet. I'll add a few more tests and let you know

**Comment by yyyogev** [comment]
@jonboydell It's redundant, you can merge.

**Comment by jonboydell** [comment]
cool - is merged into develop now

**Comment by yyyogev** [comment]
Done at https://github.com/logzio/logzio_terraform_client/pull/61
